name: Deploy Docker Image to Heroku

on:
  push:
    branches: [main]

jobs:
  test:
    name: Running E2E Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout for testing
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Run E2E Test
        run: yarn test:e2e
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}


  deploy-test:
    name: Deploy To Test Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for deploy
        uses: actions/checkout@v3

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_TEST_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: --build-arg mongourl=${{ secrets.MONGO_URL }} --build-arg dbname=${{ secrets.TEST_DB_NAME }}
          process_type: web


  deploy:
    name: Deploy To Production
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for deploy
        uses: actions/checkout@v3

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: --build-arg mongourl=${{ secrets.MONGO_URL }} --build-arg dbname=${{ secrets.DB_NAME }}
          process_type: web
